name: Deploy to Clever Cloud
on:
  pull_request_target:
    types:
      - opened
      - closed
      - synchronize
      - reopened
    branches:
      - main

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Clever Cloud
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Create or Update Clever Cloud App
        uses: CleverCloud/clever-cloud-review-app@v2.0.2
        env:
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          ORGA_ID: ${{ secrets.ORGA_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          type: "maven"
